"""rng=3 vs rng=4 prismatic-corpus diff (per ground-truth shape signatures).

Compares two manifests:

  - rng=3 baseline  : ongoing_work/prismatic_manifest_rng3_snapshot.json
                      (snapshot taken before the rng=4 sweep started)
  - rng=4 candidate : output/prismatic_manifest.json
                      (regenerated by tools/dedup_prismatic_by_shape.py
                       and tools/build_prismatic_doc.py after rng=4 finishes)

Reports:

  * Per-polytope counts (rng=3 → rng=4, delta).
  * Gainers (polytopes whose shape count grew).
  * Losers (polytopes whose count shrank — should be 0 if everything
    is preserved monotonically).
  * Total shape count diff.
  * Writes ongoing_work/rng4_gainers.json in the same format as
    rng3_gainers.json so we can chart progression rng=2 → rng=3 → rng=4.
"""

from __future__ import annotations

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

RNG3_PATH = os.path.join(ROOT, "ongoing_work", "prismatic_manifest_rng3_snapshot.json")
RNG4_PATH = os.path.join(ROOT, "output", "prismatic_manifest.json")
OUT_PATH  = os.path.join(ROOT, "ongoing_work", "rng4_gainers.json")


def _index(manifest):
    """Return dict[slug] -> n_shapes (and the underlying shape entries)."""
    out = {}
    for fam_letter, polys in manifest.get("families", {}).items():
        for poly in polys:
            slug = poly.get("slug")
            shapes = poly.get("shapes", [])
            out[slug] = {
                "n": poly.get("n_shapes", len(shapes)),
                "shapes": shapes,
                "family": fam_letter,
            }
    return out


def _shape_keys(shapes):
    """Stable per-shape identity: prefer basename (post-relabel), fallback to label+subtype."""
    keys = []
    for s in shapes:
        b = s.get("basename")
        if b:
            keys.append(b)
        else:
            keys.append(f"{s.get('label')}::{s.get('subtype')}")
    return sorted(keys)


def main():
    if not os.path.exists(RNG3_PATH):
        print(f"ERROR: snapshot not found: {RNG3_PATH}", file=sys.stderr)
        sys.exit(1)
    if not os.path.exists(RNG4_PATH):
        print(f"ERROR: rng=4 manifest not found: {RNG4_PATH}", file=sys.stderr)
        sys.exit(1)

    with open(RNG3_PATH) as f:
        m3 = json.load(f)
    with open(RNG4_PATH) as f:
        m4 = json.load(f)

    print(f"rng=3 manifest rng field: {m3.get('rng')}")
    print(f"rng=4 manifest rng field: {m4.get('rng')}")
    print()

    i3 = _index(m3)
    i4 = _index(m4)

    all_slugs = sorted(set(i3) | set(i4))

    total3 = sum(v["n"] for v in i3.values())
    total4 = sum(v["n"] for v in i4.values())

    hit3 = sum(1 for v in i3.values() if v["n"] > 0)
    hit4 = sum(1 for v in i4.values() if v["n"] > 0)

    gainers = []
    losers = []
    new_hits = []  # were 0 at rng=3, >0 at rng=4

    for slug in all_slugs:
        n3 = i3.get(slug, {}).get("n", 0)
        n4 = i4.get(slug, {}).get("n", 0)
        if n4 > n3:
            entry = {"slug": slug, "rng3": n3, "rng4": n4, "delta": n4 - n3}
            if n3 == 0:
                new_hits.append(entry)
            else:
                gainers.append(entry)
        elif n4 < n3:
            losers.append({"slug": slug, "rng3": n3, "rng4": n4, "delta": n4 - n3})

    print(f"Totals: rng=3 = {total3}  rng=4 = {total4}  delta = {total4 - total3:+d}")
    print(f"Hit polytopes: rng=3 = {hit3}  rng=4 = {hit4}  delta = {hit4 - hit3:+d}")
    print()

    if gainers:
        print(f"== Gainers (already-hit polytopes that gained shapes) — {len(gainers)} ==")
        for g in gainers:
            print(f"  {g['slug']:30s} {g['rng3']:3d} -> {g['rng4']:3d}  (+{g['delta']})")
    else:
        print("== No existing-hit polytope gained shapes ==")
    print()

    if new_hits:
        print(f"== New hits (was 0 at rng=3, >0 at rng=4) — {len(new_hits)} ==")
        for g in new_hits:
            print(f"  {g['slug']:30s} 0 -> {g['rng4']:3d}")
    else:
        print("== No new hit polytopes ==")
    print()

    if losers:
        print(f"== !! Losers (UNEXPECTED — should never happen) — {len(losers)} ==")
        for g in losers:
            print(f"  {g['slug']:30s} {g['rng3']:3d} -> {g['rng4']:3d}")
    else:
        print("== No losers (every rng=3 shape preserved) ==")
    print()

    out = {
        "rng3_total": total3,
        "rng4_total": total4,
        "rng3_hit_polytopes": hit3,
        "rng4_hit_polytopes": hit4,
        "gainers": gainers,
        "new_hits": new_hits,
        "losers": losers,
        "note": (
            "Computed by ongoing_work/probes/rng3_vs_rng4_diff.py. "
            "Identity is per-polytope shape count from prismatic_manifest.json "
            "(canonical post-dedup view). Losers should always be empty: each "
            "rng=N corpus is a superset of rng=(N-1)."
        ),
    }
    with open(OUT_PATH, "w") as f:
        json.dump(out, f, indent=2)
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
