"""Registry of all convex uniform 4-polytopes generated by Wythoff
construction on the rank-4 Coxeter groups A4, B4 (=BC4), F4, H4.

For each Coxeter group we list every nonzero bitmask in {0,1}^4. When
the diagram has a reflective automorphism (palindrome reversal), we
keep only one representative of each equivalence class.

Naming follows the Norman-Johnson scheme used on Wikipedia:
  bitmask   suffix
   1000     <regular>           (the regular 4-polytope from this family)
   0100     rectified
   1100     truncated
   0010     birectified  (= dual of rectified, often same as rectified of dual)
   1010     cantellated
   0110     bitruncated
   1110     cantitruncated
   0001     <regular dual>      (the regular dual)
   1001     runcinated
   0101     <bitmask 0101>
   1101     runcitruncated
   0011     <regular dual variants>
   1011     runcicantellated
   0111     <truncated variants>
   1111     omnitruncated

The common name used here is the Wikipedia article title.
"""
try:
    from .wythoff import COXETER_MATRICES
except ImportError:
    from wythoff import COXETER_MATRICES


def _palindromic(group: str) -> bool:
    """Return True if the Coxeter diagram has a left-right symmetry,
    i.e. m_12 == m_34."""
    M = COXETER_MATRICES[group]
    return M[0, 1] == M[2, 3]


def _all_bitmasks(group: str):
    """Yield distinct nonzero 4-tuples; for palindromic diagrams
    skip a bitmask if its reverse already appeared."""
    seen = set()
    pal = _palindromic(group)
    for n in range(1, 16):
        b = tuple((n >> i) & 1 for i in range(4))
        rev = b[::-1]
        if pal and rev in seen:
            continue
        seen.add(b)
        yield b


# Common-name table.  Keyed by (group, bitmask).
# For unnamed cases we synthesize a hyphenated descriptor.
_NAMES = {
    # ---- A4 family (palindromic 3-3-3): 9 distinct ----
    ("A4", (1, 0, 0, 0)): "5-cell",
    ("A4", (0, 1, 0, 0)): "rectified 5-cell",
    ("A4", (1, 1, 0, 0)): "truncated 5-cell",
    ("A4", (1, 0, 1, 0)): "cantellated 5-cell",
    ("A4", (0, 1, 1, 0)): "bitruncated 5-cell",
    ("A4", (1, 1, 1, 0)): "cantitruncated 5-cell",
    ("A4", (1, 0, 0, 1)): "runcinated 5-cell",
    ("A4", (1, 1, 0, 1)): "runcitruncated 5-cell",
    ("A4", (1, 1, 1, 1)): "omnitruncated 5-cell",

    # ---- B4 family (4-3-3, no automorphism): 15 distinct ----
    ("B4", (1, 0, 0, 0)): "tesseract",
    ("B4", (0, 1, 0, 0)): "rectified tesseract",
    ("B4", (1, 1, 0, 0)): "truncated tesseract",
    ("B4", (1, 0, 1, 0)): "cantellated tesseract",
    ("B4", (1, 0, 0, 1)): "runcinated tesseract",
    ("B4", (0, 1, 1, 0)): "bitruncated tesseract",
    ("B4", (1, 1, 1, 0)): "cantitruncated tesseract",
    ("B4", (1, 1, 0, 1)): "runcitruncated tesseract",
    ("B4", (1, 1, 1, 1)): "omnitruncated tesseract",
    ("B4", (0, 0, 0, 1)): "16-cell",
    ("B4", (0, 0, 1, 0)): "24-cell",  # rectified 16-cell
    ("B4", (0, 0, 1, 1)): "truncated 16-cell",
    ("B4", (0, 1, 0, 1)): "cantellated 16-cell",  # = runcinated tesseract? check
    ("B4", (0, 1, 1, 1)): "cantitruncated 16-cell",
    ("B4", (1, 0, 1, 1)): "runcitruncated 16-cell",

    # ---- F4 family (palindromic 3-4-3): 9 distinct ----
    # Note: F4 (1,0,0,0) = 24-cell, which is also B4 (0,0,1,0).
    ("F4", (1, 0, 0, 0)): "24-cell (F4)",
    ("F4", (0, 1, 0, 0)): "rectified 24-cell",
    ("F4", (1, 1, 0, 0)): "truncated 24-cell",
    ("F4", (1, 0, 1, 0)): "cantellated 24-cell",
    ("F4", (0, 1, 1, 0)): "bitruncated 24-cell",
    ("F4", (1, 1, 1, 0)): "cantitruncated 24-cell",
    ("F4", (1, 0, 0, 1)): "runcinated 24-cell",
    ("F4", (1, 1, 0, 1)): "runcitruncated 24-cell",
    ("F4", (1, 1, 1, 1)): "omnitruncated 24-cell",

    # ---- H4 family (5-3-3, no automorphism): 15 distinct ----
    ("H4", (1, 0, 0, 0)): "120-cell",
    ("H4", (0, 1, 0, 0)): "rectified 120-cell",
    ("H4", (1, 1, 0, 0)): "truncated 120-cell",
    ("H4", (1, 0, 1, 0)): "cantellated 120-cell",
    ("H4", (1, 0, 0, 1)): "runcinated 120-cell",
    ("H4", (0, 1, 1, 0)): "bitruncated 120-cell",
    ("H4", (1, 1, 1, 0)): "cantitruncated 120-cell",
    ("H4", (1, 1, 0, 1)): "runcitruncated 120-cell",
    ("H4", (1, 1, 1, 1)): "omnitruncated 120-cell",
    ("H4", (0, 0, 0, 1)): "600-cell",
    ("H4", (0, 0, 1, 0)): "rectified 600-cell",
    ("H4", (0, 0, 1, 1)): "truncated 600-cell",
    ("H4", (0, 1, 0, 1)): "cantellated 600-cell",
    ("H4", (0, 1, 1, 1)): "cantitruncated 600-cell",
    ("H4", (1, 0, 1, 1)): "runcitruncated 600-cell",
}


# Polytopes with the same underlying shape but different Coxeter
# realizations.  Searches on these would be redundant.
KNOWN_DUPLICATES = {
    # F4 24-cell = B4 rectified 16-cell
    ("F4", (1, 0, 0, 0)): ("B4", (0, 0, 1, 0)),
}


# Non-Wythoff convex uniforms (already studied separately):
NON_WYTHOFF = ["snub 24-cell", "grand antiprism"]


def all_uniform_polytopes():
    """Iterate (group, bitmask, name) for the 48 Wythoff combos.
    Caller may dedup via KNOWN_DUPLICATES."""
    for group in ("A4", "B4", "F4", "H4"):
        for b in _all_bitmasks(group):
            name = _NAMES.get((group, b), f"{group}_{''.join(map(str, b))}")
            yield (group, b, name)


def unique_uniform_polytopes():
    """Iterate, skipping known duplicates."""
    for group, b, name in all_uniform_polytopes():
        if (group, b) in KNOWN_DUPLICATES:
            continue
        yield (group, b, name)


if __name__ == "__main__":
    all_list = list(all_uniform_polytopes())
    uniq = list(unique_uniform_polytopes())
    print(f"Wythoff combos: {len(all_list)}")
    print(f"Unique (after duplicate removal): {len(uniq)}")
    print(f"Plus non-Wythoff: {NON_WYTHOFF}")
    print(f"Total convex uniform 4-polytopes: {len(uniq) + len(NON_WYTHOFF)}")
    print()
    for group, b, name in all_list:
        dup = " [DUP of {}]".format(KNOWN_DUPLICATES[(group, b)]) \
              if (group, b) in KNOWN_DUPLICATES else ""
        print(f"  {group} {b}  {name}{dup}")
